CREATE DATABASE projdb;
GO

USE projdb;
GO

CREATE TABLE CATEGORY (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(500),
    NOTES TEXT,
    ICON VARCHAR(250),
    IDPARENT BIGINT,
    SLUG VARCHAR(160),
    META_TITLE VARCHAR(100),
    META_KEYWORD VARCHAR(300),
    META_DESCRIPTION VARCHAR(300),
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    ISDELETE TINYINT,
    ISACTIVE TINYINT,

    FOREIGN KEY (IDPARENT) REFERENCES CATEGORY(ID)
);
GO

CREATE TABLE PRODUCT (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(500),
    DESCRIPTION TEXT,
    NOTES TEXT,
    IMAGE VARCHAR(550),
    IDCATEGORY BIGINT,
    CONTENTS TEXT,
    PRICE DECIMAL(18, 2),
    QUANTITY INT,
    SLUG VARCHAR(160),
    META_TITLE VARCHAR(100),
    META_KEYWORD VARCHAR(500),
    META_DESCRIPTION VARCHAR(500),
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    ISDELETE TINYINT,
    ISACTIVE TINYINT,

    FOREIGN KEY (IDCATEGORY) REFERENCES CATEGORY(ID)
);
GO

CREATE TABLE CONFIGURATIONS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(500),
    NOTES TEXT,
    ISDELETE TINYINT,
    ISACTIVE TINYINT
);
GO

CREATE TABLE PRODUCT_CONFIG (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    IDPRODUCT BIGINT,
    IDCONFIG BIGINT,
    VALUE TEXT,

    FOREIGN KEY (IDPRODUCT) REFERENCES PRODUCT(ID),

    FOREIGN KEY (IDCONFIG) REFERENCES CONFIGURATIONS(ID)
);
GO

CREATE TABLE PRODUCT_IMAGES (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(250),
    URLIMG VARCHAR(250),
    IDPRODUCT BIGINT,

    FOREIGN KEY (IDPRODUCT) REFERENCES PRODUCT(ID)
);
GO

CREATE TABLE NEWS_CATEGORY (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(500),
    NOTES TEXT,
    ICON VARCHAR(250),
    IDPARENT BIGINT,
    SLUG VARCHAR(160),
    META_TITLE VARCHAR(100),
    META_KEYWORD VARCHAR(500),
    META_DESCRIPTION VARCHAR(500),
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    ISDELETE TINYINT,
    ISACTIVE TINYINT,

    FOREIGN KEY (IDPARENT) REFERENCES NEWS_CATEGORY(ID)
);
GO

CREATE TABLE NEWS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(500),
    DESCRIPTION TEXT,
    IMAGE VARCHAR(550),
    IDNEWSCATEGORY BIGINT,
    CONTENTS TEXT,
    SLUG VARCHAR(160),
    META_TITLE VARCHAR(100),
    META_KEYWORD VARCHAR(500),
    META_DESCRIPTION VARCHAR(500),
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    ISDELETE TINYINT,
    ISACTIVE TINYINT,

    FOREIGN KEY (IDNEWSCATEGORY) REFERENCES NEWS_CATEGORY(ID)
);
GO

CREATE TABLE CUSTOMER (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(250),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(32),
    ADDRESS VARCHAR(500),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(50),
    AVATAR VARCHAR(250),
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    ISDELETE TINYINT,
    ISACTIVE TINYINT
);
GO

CREATE TABLE PAYMENT_METHOD (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(250),
    NOTES TEXT,
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    ISDELETE TINYINT,
    ISACTIVE TINYINT
);
GO

CREATE TABLE TRANSPORT_METHOD (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(250),
    NOTES TEXT,
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    ISDELETE TINYINT,
    ISACTIVE TINYINT
);
GO

CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    IDORDERS CHAR(10),
    ORDERS_DATE DATETIME,
    IDCUSTOMER BIGINT,
    IDPAYMENT BIGINT,
    IDTRANSPORT BIGINT,
    TOTAL_MONEY DECIMAL(18, 2),
    NOTES TEXT,
    NAME_RECEIVER VARCHAR(250),
    ADDRESS VARCHAR(500),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(50),
    ISDELETE TINYINT,
    ISACTIVE TINYINT,
 
    FOREIGN KEY (IDCUSTOMER) REFERENCES CUSTOMER(ID),
  
    FOREIGN KEY (IDPAYMENT) REFERENCES PAYMENT_METHOD(ID),

    FOREIGN KEY (IDTRANSPORT) REFERENCES TRANSPORT_METHOD(ID)
);
GO

CREATE TABLE ORDERS_DETAILS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    IDORD BIGINT,
    IDPRODUCT BIGINT,
    PRICE DECIMAL(18, 2),
    QTY INT,
    TOTAL DECIMAL(18, 2),
    RETURN_QTY INT,

    FOREIGN KEY (IDORD) REFERENCES ORDERS(ID),

    FOREIGN KEY (IDPRODUCT) REFERENCES PRODUCT(ID)
);
GO